image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - vadimcn.vscode-lldb
    - rust-lang.rust-analyzer
    - bungcip.better-toml
    - serayuzgur.crates
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
    - eamodio.gitlens
    