[package]
name = "rust_template"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Simpson <Joseph.Simpson@outlook.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
